version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5050:5050"
    volumes:
      - ./backend:/app
    networks:
      - pz-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    networks:
      - pz-network

networks:
  pz-network:
    driver: bridge
